/**
 * Runtime access to actual website template modules.
 * The list comes from registry.generated.ts, which is generated by scanning template folders.
 */

import type { WebsiteTemplateDefinition } from "../types";
import { GENERATED_WEBSITE_TEMPLATES } from "./registry.generated";

function validateTemplates(input: WebsiteTemplateDefinition[]) {
  const keys = new Set<string>();
  return input.filter((template) => {
    if (!template?.key || !template?.name || !template?.component) return false;
    if (keys.has(template.key)) {
      console.error(`[website/templates] Duplicate template key: ${template.key}`);
      return false;
    }
    keys.add(template.key);
    return true;
  });
}

export const WEBSITE_TEMPLATE_REGISTRY = validateTemplates(
  GENERATED_WEBSITE_TEMPLATES,
);

export function getWebsiteTemplates() {
  return WEBSITE_TEMPLATE_REGISTRY;
}

export function getDefaultWebsiteTemplate() {
  return WEBSITE_TEMPLATE_REGISTRY[0];
}

export function getWebsiteTemplate(key?: string | null) {
  return (
    WEBSITE_TEMPLATE_REGISTRY.find((template) => template.key === key) ||
    getDefaultWebsiteTemplate()
  );
}
