"use client";
import { useEffect, useState } from "react";
import type { NamedOption, PickupAuthorizationView } from "../advanced-shared";
import { AdvancedIdentityStyles } from "../advanced-shared";
export type PickupAuthorizationDraft = Omit<PickupAuthorizationView,"id"|"status"> & {id?:string;status?:string};
const empty:PickupAuthorizationDraft={studentId:"",authorizedPersonType:"parent",fullName:"",phone:"",relationship:"",recurring:true,allowedDays:[],note:""};
export function PickupAuthorizationForm({value,students=[],saving=false,primaryColor,onSubmit,onCancel}:{value?:Partial<PickupAuthorizationDraft>|null;students?:readonly NamedOption[];saving?:boolean;primaryColor?:string;onSubmit:(value:PickupAuthorizationDraft)=>void;onCancel?:()=>void}) {
 const [form,setForm]=useState<PickupAuthorizationDraft>({...empty,...value}); useEffect(()=>setForm({...empty,...value}),[value]);
 const patch=<K extends keyof PickupAuthorizationDraft>(key:K,v:PickupAuthorizationDraft[K])=>setForm(c=>({...c,[key]:v}));
 const submit=(e:React.FormEvent)=>{e.preventDefault();if(!form.studentId||!form.fullName?.trim())return;onSubmit({...form,fullName:form.fullName.trim(),phone:form.phone?.trim()||null,relationship:form.relationship?.trim()||null})};
 return <form className="ai-form ai-card" onSubmit={submit}><AdvancedIdentityStyles primaryColor={primaryColor}/><div className="ai-form-grid"><label className="ai-field"><span>Student</span><select value={form.studentId} onChange={e=>patch("studentId",e.target.value)} required><option value="">Select student</option>{students.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label><label className="ai-field"><span>Person type</span><select value={form.authorizedPersonType} onChange={e=>patch("authorizedPersonType",e.target.value as PickupAuthorizationDraft["authorizedPersonType"])}><option value="parent">Parent</option><option value="guardian">Guardian</option><option value="other">Other</option></select></label><label className="ai-field"><span>Full name</span><input value={form.fullName||""} onChange={e=>patch("fullName",e.target.value)} required/></label><label className="ai-field"><span>Phone</span><input value={form.phone||""} onChange={e=>patch("phone",e.target.value)}/></label><label className="ai-field"><span>Relationship</span><input value={form.relationship||""} onChange={e=>patch("relationship",e.target.value)}/></label><label className="ai-field"><span>Valid until</span><input type="date" value={typeof form.validUntil==="string"?form.validUntil:""} onChange={e=>patch("validUntil",e.target.value)}/></label><label className="ai-field full"><span>Note</span><textarea value={form.note||""} onChange={e=>patch("note",e.target.value)}/></label></div><div className="ai-actions" style={{justifyContent:"flex-end"}}>{onCancel?<button type="button" onClick={onCancel}>Cancel</button>:null}<button className="primary" disabled={saving}>{saving?"Saving…":"Save authorization"}</button></div></form>
}
export default PickupAuthorizationForm;
