/** Local-first advanced timetable and scheduling stores. */
export const ADVANCED_SCHEDULING_STORES: Record<string, string> = {
  schedulePeriodTemplates: "id,accountId,schoolId,branchId,name,isDefault,active,isDeleted,updatedAt,synced",
  schedulePeriodTemplateAssignments: "id,accountId,schoolId,branchId,periodTemplateId,scopeType,scopeId,effectiveFrom,effectiveTo,active,isDeleted,updatedAt,synced",
  schedulePeriodSlots: "id,accountId,schoolId,branchId,periodTemplateId,dayOfWeek,slotType,startMinute,endMinute,order,teachable,active,isDeleted,updatedAt,synced",
  scheduleSharedBlocks: "id,accountId,schoolId,branchId,periodTemplateId,blockType,dayOfWeek,periodSlotId,startMinute,endMinute,required,active,isDeleted,updatedAt,synced",
  scheduleSharedBlockGroups: "id,accountId,schoolId,branchId,sharedBlockId,groupId,active,isDeleted,updatedAt,synced,[sharedBlockId+groupId]",
  scheduleSharedBlockTeachers: "id,accountId,schoolId,branchId,sharedBlockId,teacherId,role,active,isDeleted,updatedAt,synced,[sharedBlockId+teacherId]",
  scheduleGroups: "id,accountId,schoolId,branchId,name,groupType,scopeType,scopeId,active,isDeleted,updatedAt,synced",
  scheduleGroupMembers: "id,accountId,schoolId,branchId,groupId,memberType,memberId,active,isDeleted,updatedAt,synced,[groupId+memberType+memberId]",
  scheduleTeacherAvailability: "id,accountId,schoolId,branchId,teacherId,dayOfWeek,periodSlotId,startMinute,endMinute,availabilityType,active,isDeleted,updatedAt,synced",
  scheduleTeacherWorkloadRules: "id,accountId,schoolId,branchId,teacherId,strength,active,isDeleted,updatedAt,synced",
  scheduleSubjectRequirements: "id,accountId,schoolId,branchId,timetableId,classId,subjectId,classSubjectId,deliveryGrouping,combinationPolicy,priority,active,isDeleted,updatedAt,synced",
  scheduleRequirementGroups: "id,accountId,schoolId,branchId,requirementId,groupId,active,isDeleted,updatedAt,synced,[requirementId+groupId]",
  scheduleRequirementTeachers: "id,accountId,schoolId,branchId,requirementId,teacherId,role,required,active,isDeleted,updatedAt,synced,[requirementId+teacherId]",
  scheduleResourceRequirements: "id,accountId,schoolId,branchId,requirementId,resourceId,required,active,isDeleted,updatedAt,synced,[requirementId+resourceId]",
  scheduleConstraintRules: "id,accountId,schoolId,branchId,category,strength,scopeType,scopeId,ruleKey,active,isDeleted,updatedAt,synced",
  scheduleSessionGroups: "id,accountId,schoolId,branchId,sessionId,groupId,active,isDeleted,updatedAt,synced,[sessionId+groupId]",
  scheduleSessionTeachers: "id,accountId,schoolId,branchId,sessionId,teacherId,role,active,isDeleted,updatedAt,synced,[sessionId+teacherId]",
  scheduleSessionResources: "id,accountId,schoolId,branchId,sessionId,resourceId,active,isDeleted,updatedAt,synced,[sessionId+resourceId]",
  scheduleGenerationRuns: "id,accountId,schoolId,branchId,timetableId,status,startedAt,completedAt,requestedByUserId,active,isDeleted,updatedAt,synced",
  scheduleDrafts: "id,accountId,schoolId,branchId,timetableId,generationRunId,status,score,rank,locked,active,isDeleted,updatedAt,synced",
  scheduleDraftSessions: "id,accountId,schoolId,branchId,draftId,requirementId,periodSlotId,dayOfWeek,startMinute,endMinute,subjectId,placementSource,locked,score,active,isDeleted,updatedAt,synced",
  scheduleDraftSessionGroups: "id,accountId,schoolId,branchId,draftSessionId,groupId,active,isDeleted,updatedAt,synced,[draftSessionId+groupId]",
  scheduleDraftSessionTeachers: "id,accountId,schoolId,branchId,draftSessionId,teacherId,role,active,isDeleted,updatedAt,synced,[draftSessionId+teacherId]",
  scheduleDraftSessionResources: "id,accountId,schoolId,branchId,draftSessionId,resourceId,active,isDeleted,updatedAt,synced,[draftSessionId+resourceId]",
  scheduleGenerationIssues: "id,accountId,schoolId,branchId,generationRunId,draftId,issueType,severity,requirementId,active,isDeleted,updatedAt,synced",
  scheduleGenerationSuggestions: "id,accountId,schoolId,branchId,generationRunId,draftId,suggestionType,status,approvedAt,active,isDeleted,updatedAt,synced",
  scheduleSuggestionRequirements: "id,accountId,schoolId,branchId,suggestionId,requirementId,active,isDeleted,updatedAt,synced,[suggestionId+requirementId]",
  scheduleSuggestionGroups: "id,accountId,schoolId,branchId,suggestionId,groupId,active,isDeleted,updatedAt,synced,[suggestionId+groupId]",
  scheduleSuggestionTeachers: "id,accountId,schoolId,branchId,suggestionId,teacherId,active,isDeleted,updatedAt,synced,[suggestionId+teacherId]",
  scheduleSuggestionResources: "id,accountId,schoolId,branchId,suggestionId,resourceId,active,isDeleted,updatedAt,synced,[suggestionId+resourceId]",
  schedulePublishEvents: "id,accountId,schoolId,branchId,timetableId,draftId,versionNumber,status,publishedAt,publishedByUserId,active,isDeleted,updatedAt,synced",
  scheduleVersionSnapshots: "id,accountId,schoolId,branchId,timetableId,draftId,versionNumber,publishedAt,active,isDeleted,updatedAt,synced,[timetableId+versionNumber]",
};
