/**
 * app/lib/websites/sections/sectionDefaults.ts
 * --------------------------------------------------------------------------
 * Default section labels, order and reusable section capability presets.
 */

import type {
  WebsiteSectionCapability,
  WebsiteSectionDefinition,
} from "./sectionTypes";
import type { WebsiteSectionKey } from "../types";

export const DEFAULT_WEBSITE_SECTION_ORDER: readonly WebsiteSectionKey[] = [
  "hero",
  "statistics",
  "about",
  "principal",
  "academic_structures",
  "programs",
  "subjects",
  "organizations",
  "teachers",
  "highlights",
  "announcements",
  "events",
  "gallery",
  "contact",
  "footer",
] as const;

export const SECTION_CAPABILITIES = {
  content: {
    supportsMedia: false,
    supportsCustomHeading: true,
    supportsCustomBody: true,
    supportsVariant: true,
    supportsOrdering: true,
    supportsNavigation: true,
  },
  mediaContent: {
    supportsMedia: true,
    supportsCustomHeading: true,
    supportsCustomBody: true,
    supportsVariant: true,
    supportsOrdering: true,
    supportsNavigation: true,
  },
  system: {
    supportsMedia: false,
    supportsCustomHeading: false,
    supportsCustomBody: false,
    supportsVariant: true,
    supportsOrdering: true,
    supportsNavigation: false,
  },
} as const satisfies Record<string, WebsiteSectionCapability>;

export const WEBSITE_SECTION_DEFAULTS: readonly WebsiteSectionDefinition[] = [
  {
    key: "hero",
    defaultLabel: "Welcome",
    defaultNavigationLabel: "Home",
    description: "Primary school introduction, call-to-action and hero media.",
    sourceType: "school",
    dataKey: "website",
    visibilitySetting: "showHero",
    navigationMode: "always",
    defaultVisible: true,
    defaultOrder: 0,
    capability: SECTION_CAPABILITIES.mediaContent,
  },
  {
    key: "statistics",
    defaultLabel: "Our School at a Glance",
    description: "Shared school statistics such as students, teachers, classes and subjects.",
    sourceType: "statistics",
    dataKey: "statistics",
    visibilitySetting: "showStatistics",
    labelSetting: "statisticsLabel",
    navigationMode: "never",
    defaultVisible: true,
    defaultOrder: 1,
    capability: SECTION_CAPABILITIES.system,
  },
  {
    key: "about",
    defaultLabel: "About Our School",
    defaultNavigationLabel: "About",
    description: "School profile, mission, values and general introduction.",
    sourceType: "school",
    dataKey: "school",
    visibilitySetting: "showAbout",
    labelSetting: "aboutLabel",
    navigationMode: "when_visible",
    defaultVisible: true,
    defaultOrder: 2,
    capability: SECTION_CAPABILITIES.mediaContent,
  },
  {
    key: "principal",
    aliases: ["leadership_message"],
    defaultLabel: "Headteacher's Welcome",
    description: "Principal or headteacher profile and welcome message.",
    sourceType: "principal",
    dataKey: "principal",
    visibilitySetting: "showPrincipal",
    labelSetting: "principalLabel",
    navigationMode: "never",
    defaultVisible: true,
    defaultOrder: 3,
    capability: SECTION_CAPABILITIES.mediaContent,
  },
  {
    key: "academic_structures",
    aliases: ["academicStructures"],
    defaultLabel: "Academic Structure",
    description: "Academic levels, divisions or structures offered by the school.",
    sourceType: "custom",
    dataKey: "academicStructures",
    visibilitySetting: "showAcademicStructures",
    labelSetting: "academicStructuresLabel",
    navigationMode: "when_visible",
    defaultVisible: true,
    defaultOrder: 4,
    capability: SECTION_CAPABILITIES.mediaContent,
  },
  {
    key: "programs",
    aliases: ["programmes"],
    defaultLabel: "Programmes",
    defaultNavigationLabel: "Academics",
    description: "Programmes, pathways or broad learning offerings.",
    sourceType: "programs",
    dataKey: "programs",
    visibilitySetting: "showPrograms",
    labelSetting: "programsLabel",
    navigationMode: "when_visible",
    defaultVisible: true,
    defaultOrder: 5,
    capability: SECTION_CAPABILITIES.mediaContent,
  },
  {
    key: "subjects",
    defaultLabel: "Subjects We Offer",
    description: "Subjects or courses available to learners.",
    sourceType: "subjects",
    dataKey: "subjects",
    visibilitySetting: "showSubjects",
    labelSetting: "subjectsLabel",
    navigationMode: "when_visible",
    defaultVisible: true,
    defaultOrder: 6,
    capability: SECTION_CAPABILITIES.mediaContent,
  },
  {
    key: "organizations",
    aliases: ["organisations", "school_life"],
    defaultLabel: "School Life",
    description: "Departments, houses, clubs, faculties and school communities.",
    sourceType: "organizations",
    dataKey: "organizations",
    visibilitySetting: "showOrganizations",
    labelSetting: "organizationsLabel",
    navigationMode: "when_visible",
    defaultVisible: true,
    defaultOrder: 7,
    capability: SECTION_CAPABILITIES.mediaContent,
  },
  {
    key: "teachers",
    aliases: ["leadership", "staff"],
    defaultLabel: "Meet Our Teachers",
    description: "Teacher and staff profiles.",
    sourceType: "teachers",
    dataKey: "teachers",
    visibilitySetting: "showTeachers",
    labelSetting: "teachersLabel",
    navigationMode: "when_visible",
    defaultVisible: true,
    defaultOrder: 8,
    capability: SECTION_CAPABILITIES.mediaContent,
  },
  {
    key: "highlights",
    aliases: ["portal_highlights"],
    defaultLabel: "School Highlights",
    description: "Curated school highlights, achievements and featured stories.",
    sourceType: "portal_highlights",
    dataKey: "highlights",
    visibilitySetting: "showHighlights",
    labelSetting: "highlightsLabel",
    navigationMode: "when_visible",
    defaultVisible: true,
    defaultOrder: 9,
    capability: SECTION_CAPABILITIES.mediaContent,
  },
  {
    key: "announcements",
    aliases: ["news"],
    defaultLabel: "Latest News",
    description: "Published announcements and school news.",
    sourceType: "announcements",
    dataKey: "announcements",
    visibilitySetting: "showAnnouncements",
    labelSetting: "announcementsLabel",
    navigationMode: "when_visible",
    defaultVisible: true,
    defaultOrder: 10,
    capability: SECTION_CAPABILITIES.mediaContent,
  },
  {
    key: "events",
    aliases: ["calendar_events"],
    defaultLabel: "Upcoming Events",
    description: "Public calendar events and important school dates.",
    sourceType: "calendar_events",
    dataKey: "events",
    visibilitySetting: "showEvents",
    labelSetting: "eventsLabel",
    navigationMode: "when_visible",
    defaultVisible: true,
    defaultOrder: 11,
    capability: SECTION_CAPABILITIES.mediaContent,
  },
  {
    key: "gallery",
    aliases: ["media_gallery"],
    defaultLabel: "School Gallery",
    description: "Website-visible school images and media.",
    sourceType: "media_gallery",
    dataKey: "gallery",
    visibilitySetting: "showGallery",
    labelSetting: "galleryLabel",
    navigationMode: "when_visible",
    defaultVisible: true,
    defaultOrder: 12,
    capability: SECTION_CAPABILITIES.mediaContent,
  },
  {
    key: "contact",
    defaultLabel: "Contact Us",
    defaultNavigationLabel: "Contact",
    description: "Public address, phone, email, map and contact actions.",
    sourceType: "contact",
    dataKey: "contact",
    visibilitySetting: "showContact",
    labelSetting: "contactLabel",
    navigationMode: "when_visible",
    defaultVisible: true,
    defaultOrder: 13,
    capability: SECTION_CAPABILITIES.content,
  },
  {
    key: "footer",
    defaultLabel: "Footer",
    description: "Footer identity, links, legal text and Eleeveon attribution.",
    sourceType: "footer",
    dataKey: "footer",
    visibilitySetting: "showFooter",
    navigationMode: "never",
    defaultVisible: true,
    defaultOrder: 14,
    capability: SECTION_CAPABILITIES.system,
  },
] as const;
