"use client";
import { useState } from "react";
import type { IdentityAccessPointOption, IdentityDeviceCapability, IdentityDeviceDraft, IdentityDeviceStatus, IdentityDeviceType } from "../infrastructure-types";
const CAPS:IdentityDeviceCapability[]=["qr_scan","barcode_scan","nfc_read","rfid_read","fingerprint_match","face_match","gps_capture","photo_capture","signature_capture"];
export function DeviceForm({accessPoints=[],initialValue,onSubmit,disabled=false,submitLabel="Save device"}:{accessPoints?:readonly IdentityAccessPointOption[];initialValue?:Partial<IdentityDeviceDraft>;onSubmit:(d:IdentityDeviceDraft)=>void|Promise<void>;disabled?:boolean;submitLabel?:string}){
 const[name,setName]=useState(initialValue?.name??"");const[code,setCode]=useState(initialValue?.code??"");const[type,setType]=useState<IdentityDeviceType>(initialValue?.deviceType??"phone");const[status,setStatus]=useState<IdentityDeviceStatus>(initialValue?.status??"offline");const[ap,setAp]=useState(initialValue?.accessPointId??"");const[serial,setSerial]=useState(initialValue?.serialNumber??"");const[provider,setProvider]=useState(initialValue?.provider??"");const[platform,setPlatform]=useState(initialValue?.platform??"");const[app,setApp]=useState(initialValue?.appVersion??"");const[firm,setFirm]=useState(initialValue?.firmwareVersion??"");const[loc,setLoc]=useState(initialValue?.locationLabel??"");const[caps,setCaps]=useState<IdentityDeviceCapability[]>(initialValue?.capabilities??[]);
 const toggle=(c:IdentityDeviceCapability)=>setCaps(v=>v.includes(c)?v.filter(x=>x!==c):[...v,c]);
 return <form onSubmit={async e=>{e.preventDefault();if(!name.trim())return;await onSubmit({name:name.trim(),code:code||null,deviceType:type,status,accessPointId:ap||null,serialNumber:serial||null,provider:provider||null,platform:platform||null,appVersion:app||null,firmwareVersion:firm||null,locationLabel:loc||null,capabilities:caps,active:status!=="disabled"})}} style={{display:"grid",gap:10}}>
 <label>Name<input value={name} onChange={e=>setName(e.target.value)} disabled={disabled} required/></label><label>Code<input value={code} onChange={e=>setCode(e.target.value)} disabled={disabled}/></label>
 <label>Type<select value={type} onChange={e=>setType(e.target.value as IdentityDeviceType)} disabled={disabled}>{["phone","tablet","computer","kiosk","qr_scanner","barcode_scanner","fingerprint_scanner","face_terminal","nfc_reader","rfid_reader","vehicle_gateway","gps_tracker","api_gateway","other"].map(v=><option key={v} value={v}>{v.replaceAll("_"," ")}</option>)}</select></label>
 <label>Status<select value={status} onChange={e=>setStatus(e.target.value as IdentityDeviceStatus)} disabled={disabled}>{["online","offline","maintenance","disabled"].map(v=><option key={v}>{v}</option>)}</select></label>
 <label>Access point<select value={ap??""} onChange={e=>setAp(e.target.value)} disabled={disabled}><option value="">None</option>{accessPoints.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>
 <label>Serial<input value={serial} onChange={e=>setSerial(e.target.value)}/></label><label>Provider<input value={provider} onChange={e=>setProvider(e.target.value)}/></label><label>Platform<input value={platform} onChange={e=>setPlatform(e.target.value)}/></label><label>App version<input value={app} onChange={e=>setApp(e.target.value)}/></label><label>Firmware<input value={firm} onChange={e=>setFirm(e.target.value)}/></label><label>Location<input value={loc} onChange={e=>setLoc(e.target.value)}/></label>
 <fieldset><legend>Capabilities</legend><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{CAPS.map(c=><label key={c}><input type="checkbox" checked={caps.includes(c)} onChange={()=>toggle(c)}/>{c.replaceAll("_"," ")}</label>)}</div></fieldset>
 <button disabled={disabled||!name.trim()}>{submitLabel}</button></form>;
}
export default DeviceForm;
