"use client";
import { useMemo,useState } from "react";
import type { IdentityAccessPointOption, IdentityDevice, IdentityDeviceStatus, IdentityDeviceType } from "../infrastructure-types";
import { DeviceCard } from "./DeviceCard";
export function DeviceList({devices,accessPoints=[],onOpen}:{devices:readonly IdentityDevice[];accessPoints?:readonly IdentityAccessPointOption[];onOpen?:(d:IdentityDevice)=>void}){
 const[q,setQ]=useState("");const[status,setStatus]=useState<IdentityDeviceStatus|"all">("all");const[type,setType]=useState<IdentityDeviceType|"all">("all");
 const map=useMemo(()=>new Map(accessPoints.map(a=>[a.id,a])),[accessPoints]);
 const rows=useMemo(()=>devices.filter(d=>!d.isDeleted).filter(d=>status==="all"||(d.status??"offline")===status).filter(d=>type==="all"||d.deviceType===type).filter(d=>[d.name,d.code,d.serialNumber,d.provider,d.platform,d.locationLabel].join(" ").toLowerCase().includes(q.toLowerCase())).sort((a,b)=>a.name.localeCompare(b.name)),[devices,q,status,type]);
 return <section style={{display:"grid",gap:10}}><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search devices..." style={{flex:1,minWidth:180}}/><select value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="all">All statuses</option><option value="online">Online</option><option value="offline">Offline</option><option value="maintenance">Maintenance</option><option value="disabled">Disabled</option></select><select value={type} onChange={e=>setType(e.target.value as typeof type)}><option value="all">All types</option><option value="phone">Phone</option><option value="tablet">Tablet</option><option value="computer">Computer</option><option value="kiosk">Kiosk</option><option value="qr_scanner">QR scanner</option><option value="barcode_scanner">Barcode scanner</option><option value="fingerprint_scanner">Fingerprint scanner</option><option value="face_terminal">Face terminal</option><option value="nfc_reader">NFC reader</option><option value="rfid_reader">RFID reader</option><option value="vehicle_gateway">Vehicle gateway</option><option value="gps_tracker">GPS tracker</option><option value="api_gateway">API gateway</option><option value="other">Other</option></select></div><div style={{display:"grid",gap:8,gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,270px),1fr))"}}>{rows.map(d=><DeviceCard key={d.id} device={d} accessPoint={d.accessPointId?map.get(d.accessPointId):null} onOpen={onOpen}/>)}</div>{!rows.length?<small>No matching devices.</small>:null}</section>;
}
export default DeviceList;
